// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace IWantApp.Models
{
    public partial class ApplicationDbContextModel
    {
        private ApplicationDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b085a556-99d0-4397-83c0-291f165020cd"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var product = ProductEntityType.Create(this);

            ProductEntityType.CreateForeignKey1(product, category);

            CategoryEntityType.CreateAnnotations(category);
            ProductEntityType.CreateAnnotations(product);

            AddAnnotation("ProductVersion", "9.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
