// <auto-generated />
using IWantApp.Infra.Data;
using IWantApp.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationDbContext), typeof(ApplicationDbContextModel))]
